environment:
  name: prod
  project: cdf-bootcamp-61-prod # ex. cdf-bootcamp-01-prod
  type: prod # prod, staging, dev, prod, qa
  selected:
  - modules/bootcamp/data_foundation
  - modules/bootcamp/ice_cream_api
  - modules/bootcamp/use_cases/oee

variables:
  modules:
    bootcamp:

      CDF_PROJECT: cdf-bootcamp-61-prod # ex. cdf-bootcamp-01-prod
      IDP_CLIENT_ID: ${IDP_CLIENT_ID} # replaced by .env
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET} # replaced by .env
      IDP_TENANT_ID: ${IDP_TENANT_ID} # replaced by .env
      CDF_URL: https://westeurope-1.cognitedata.com # This is related to the cluster where the CDF project is hosted.
      IDP_SCOPES: https://westeurope-1.cognitedata.com/.default
      IDP_TOKEN_URL: ${IDP_TOKEN_URL} # replaced by .env
      location_name: abcd
      source_name: abcde
      scheduleHourly: 1 1 * * *
      # pause_transformations: ''
  # Groups
      data_developer_source_id: 51e88e4c-e65c-4ffc-89d2-11d1ab8b6bba # ex. xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
      data_pipeline_oee_source_id: 593789b1-9437-46a4-ae6f-2099491be385 # ex. xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
      readwrite_source_id: bd0e24ac-4386-430f-b722-50b220332665  # ex. xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
      readonly_source_id: bd0e24ac-4386-430f-b722-50b220332665  # ex. xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
      icapi_extractors_source_id: c9c1631c-ee64-4b65-b19b-abf93f7c3682 # ex. xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx

  # Client Ids
      data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID} # replaced by .env
      data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET} # replaced by .env

      icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID} # replaced by .env
      icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET} # replaced by .env

      icapi_ds_external_id: ds_icapi
      use_cases:
        oee:
          uc_oee_ds_external_id: ds_uc_oee